rootProject.name = "slinkt"

include(":kotlin:stdlib")
include(":kotlin:reflect")
include(":kotlin:compiler-embeddable")
include(":kotlin:coroutines-core")
include(":kotlin:coroutines-core-jvm")
include(":kotlin:script-runtime")
include(":kotlin:script-util")
include(":kotlin:scripting-common")
include(":kotlin:scripting-jvm")
include(":kotlin:scripting-jvm-host")
include(":kotlin:scripting-compiler")
include(":kotlin:scripting-compiler-embeddable")
include(":kotlin:scripting-compiler-impl-embeddable")
